name: srv-id
group: newtengroup
owner: eden-framework
version: 0.0.0
description: id generation service of infrastructure
program_language: golang
workflow:
  extends: feature-pr-no-test
scripts:
  build:
  - go build -v -o ./build/$PROJECT_NAME ./cmd
  - eden generate openapi
  test: go test ./cmd
